spring.application.name=wms-mori

# --- CONFIGURAÇÃO DO BANCO NEON (NUVEM) ---

# A URL limpa (sem usuário/senha aqui)
spring.datasource.url=jdbc:postgresql://ep-dawn-grass-ahc1gpkq-pooler.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require

# As credenciais separadas (O Spring vai usar estas!)
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Fvpnw3ZyV8bC

spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / HIBERNATE ---
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# "update" cria as tabelas automaticamente se não existirem
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true